[package]
name = "shamirs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
math = { package = "winter-math", version = "0.3", default-features = false }

